<?php

function poroscopo_create_string() {

$frase1 = array(
"Oggi non potrai fare a meno di parlare a tutti",
"Sorpresa! Oggi preparati al ritorno",
"Nessuna paura, oggi la tua vita risentira'",
"Oggi non potrai fare a meno",
"Le Stelle oggi parlano",
"La giornata di oggi avra' il gusto",
"Gli Astri rivelano che avrai bisogno del conforto",
"Oggi aspettati una giornata campale grazie all'influenza",
"Finalmente e' giunto il momento di scoprire la bellezza",
"Le Stelle ti vogliono aiutare, quindi e' meglio che tu trovi tutti i lati positivi",
"Le Stelle ti consigliano di non sospettare",
"Oggi farai caso all'importanza",
"Certo che oggi non potrai lamentarti",
"Anche se per te e' strano, oggi sentirai la mancanza",
"Certo che la vita e' strana, non avresti mai pensato di aver bisogno",
"Da mattina a sera, questa sara' la giornata",
"Sveglia! Ti sei dimenticato",
"Venere dice: ricordati",
"I tuoi cari si arrabbieranno con te a causa",
"Il tuo partner si arrabbiera' ricordandosi",
"Rivela agli altri quello che provi, in questo modo potrai approfittare",
"Attenzione! Non puoi farti gioco",
"Non puoi trascurare l'importanza",
"In questo periodo la tua vita scorre in funzione",
"Intorno a te senti l'assedio",
"Oggi non serve che tu approfitti",
"Fa' attenzione alle insidie",
"In questi giorni senti il peso",
"Perche' non ti senti a posto? Scopri il vero significato",
"Le Stelle ti rimproverano! Non ti sei ancora accorto di avere bisogno",
"La Luna in Saturno e' colma",
"L'Ariete in Gemelli e' foriero",
"La Luna eclissata da Giove agisce ricordandoti",
"Da oggi, per te, l'amore crescera' in funzione",
"Per non aver problemi di denaro, oggi abbi cura",
"Ti preoccupi per la salute? Non e' quello il problema, piuttosto prenditi cura",
"Le Stelle parlano del tuo lavoro; per realizzarti hai bisogno",
"E' un periodo di alti e bassi, tutto per colpa",
"Un anomalo disallineamento tra i pianeti sara' la causa",
"Il Sole e entrera' in opposizione con il Cinghiale Minore: avrai paura",
"Oggi la Luna transitera' per la costellazione del Siluro, segno",
"La probabile collisione odierna tra la Luna e Venere sara' la causa",
"Plutone, passando nei Pesci, si e' accorto",
"Proprio quando tutto va male, ricordati che le Stelle possono farti dono",
"Oggi scoprirai che il tuo partner non ti ha mai detto nulla",
"Ti sembrera' strano, ma qualcosa si cela dietro alla semplicita'",
"La vita e' un labirinto e per uscirne hai bisogno",
"I satelliti di Giove si avvicinano alla Luna: vuol dire che sei in attesa",
"Lo Scorpione in Gemelli non ti riparera' dagli effetti",
"Come avevi previsto, continua il periodo",
"Prima che il sole tramonti, ti accorgerai",
"E' in arrivo un bastimento carico",
"Mercurio e' ascendente su Urano, quindi ti caricherai",
"Nettuno sta transitando nella nebulosa Staller: vivrai con lo stupore",
"L'orbita di Saturno e' otturata dalla presenza",
"Puoi leggere nelle Stelle i segni",
"In questo periodo dell'anno i segni di terra e di aria saranno in contrasto con quelli",
"In questo periodo dell'anno i segni di fuoco e di acqua saranno in sintonia con quelli",
"Il movimento del Sole sull'Orsa Minore e' lo stesso",
"L'orbita di Saturno nel tuo segno traccia la forma",
"Il passaggio di Mercurio nella nebulosa M51 cela il mistero",
"Le Stelle dimostrano di volerti bene prendendosi gioco",
"Le Stelle la sanno lunga e conoscono i segreti",
"Grazie al Cielo benigno, sarai circondato dal profumo",
"Il cielo di Urano si e' accorto che passi troppo tempo in compagnia",
"Grazie a combinazioni astrali anomale, non potrai bearti",
"Il movimento astrale di Plutone segnala il rischio",
"I vapori tossici su Venere entrano nella costellazione dell'Asinello: risentirai",
"Le costellazioni dell'Orsa Maggiore e Minore ti parlano",
"Oggi il postino transitera' nella costellazione della Bilancia, percio' risentirai",
"La costellazione del cane ti mette di fronte alla realta'",
"Le galassie in congiunzione con Cassiopea sono segno",
"Secondo i calcoli astrali degli Aztechi, oggi sara' enorme l'influenza",
"Secondo i sistemi astrali dell'antica Mesopotamia, oggi aspettati l'arrivo",
"Osservando i corpi celesti secondo gli antichi calcoli del Celti, subirai gli effetti",
"I calcoli astrali dei Maya prevedono per te il ritorno",
"Hai messo troppa carne al fuoco ed adesso su di te hai il peso",
"Il calendario dei Maya segnala per oggi",
"Oggi per quelli del tuo segno la congiunzione di Urano con la cometa di Halley indica"
);

$frase2 = array(
"della simpatia di chi ti sta intorno",
"degli incontri inaspettati",
"degli sviluppi futuri",
"di un momento di riposo",
"dei rimpianti che tenti di celare",
"degli investimenti in Antartide",
"degli investimenti in allevamenti di paguri",
"del desiderio di essere protagonista",
"dei viaggi che sogni da tempo",
"delle vacanze estive",
"della tristezza che ti opprime",
"delle lagrime che scendono copiose",
"delle liti scatenate in famiglia",
"dei sogni nel cassetto",
"delle ambizioni che ti stimolano",
"dei disturbi intestinali",
"dei ripensamenti che hai in continuazione",
"della fortuna che ti assiste",
"della buona sorte",
"della sfortuna nera",
"dei sentimenti altrui",
"delle attenzioni che non ti sono state rivolte",
"delle attenzioni che non meriti",
"dei raffreddori da cavallo",
"delle favole della buona notte",
"delle vecchie e care ninne-nanne",
"delle incazzature che covi dentro",
"della gioia di un incontro a lungo desiderato",
"della serenita' di un clistere",
"della gioia di una vacanza lontano da qui",
"dei bei ricordi di quando eri intelligente",
"delle occasioni mancate",
"della sagra del porcino",
"della tua stitichezza cronica",
"del calore di un abbraccio",
"degli incoraggiamenti dei colleghi",
"di un futuro spregiudicato",
"delle strane macchie marroni sulle tende del bagno",
"della macchina che hai dimenticato in seconda fila",
"della copertina de''L'Espresso'' con la solita donna nuda",
"dei meteurismi che ti stanno perseguitando",
"delle tue strane preferenze sessuali",
"di un ritorno alla gioventu'",
"di una colite spastica",
"dei soliti incontri con gli alieni",
"di una dose eccessiva di barbiturici",
"del cingolato parcheggiato sopra la tua macchina",
"di una notte di dolce riposo",
"di una notte di bagordi",
"della vegetazione che ti cresce addosso",
"di delitti efferati",
"di tanto tanto tanto amore",
"di una languida dolcezza ineffabile",
"di tanta insoddisfazione",
"dei piatti da lavare",
"della mancanza di spirito",
"di una rivelazione sorprendente",
"di un salto nel buio",
"della nebbia in Val Padana",
"del sorriso del mare",
"del profumo dei fiori recisi",
"dell'allergia al miele di acacia",
"della fragranza di un saccottino",
"della pressione atmosferica",
"delle mutande di due taglie piu' strette",
"dell'umidita'",
"della visita del tuo trisavolo",
"della tua doppia personalita'",
"del tuo lato piu' femminile",
"della fedina penale",
"delle speranze covate a lungo",
"delle speranze per cui vivi",
"del sole splendente d'estate",
"delle tendenze cleptomani",
"degli incubi notturni",
"dell'alba di un giorno nuovo",
"del periodo della muta",
"delle tasse da pagare",
"della leggerezza di un sospiro",
"di un profondo ripensamento",
"di un oscuro presentimento",
"di una gravidanza isterica",
"del vero lavoro di tua madre",
"del turgore dei tuoi capezzoli"
);

$frase3 = array(
"Ma, non temere, puoi far fronte a tutto con",
"Ma, non scoraggiarti, saprai riprenderti sfruttando",
"Ma il destino ti donera'",
"Ma, non temere, farai faville con",
"Cerca di arrivare a domani sano e salvo con",
"Sarai costretto a superare i tuoi limiti; per farlo, dovrai sfruttare",
"Il sole tornera' di nuovo a splendere quando vedrai",
"Le stelle dicono anche che non potrai sfruttare",
"Oltre a questo, alcune persone ti invidieranno",
"Niente paura, pero', la vita e' come",
"Lascia tutte le tue speranze e dimentica",
"I tuoi problemi si risolveranno domani, ma senza",
"Il segreto del tuo successo sara'",
"Risolverai i tuoi problemi con",
"In effetti, farai anche notare a tutti",
"E' proprio colpa delle stelle se non trovi piu'",
"D'altronde, come puoi vivere senza",
"E' tempo di farsi notare con",
"Probabilmente e' perche' non sfrutti a fondo",
"Gli astri influenzeranno negativamente",
"Fatti aiutare, perche' e' sbagliato desiderare",
"Riscopri la tua personalita' tramite",
"Prova a cercare il vero senso della vita dentro",
"Considera anche che questa settimana sara' come",
"Il nuovo mese, inoltre, ti fara' venire in mente",
"Forse sei troppo nervoso e non tieni abbastanza in conto",
"Hai paura del futuro? Non devi! Usa",
"In realta' c'e' poco da fare, non c'e' posto per",
"Il cielo vuole anche suggerirti una cosa: la tua rinascita sara' come",
"Togliti subito dalla mente",
"Scavandoti dentro troverai",
"Non hai cura di te! Non hai neanche notato",
"Aiuta il tuo prossimo regalandogli",
"Avrai il successo che meriti e...",
"Non e' colpa delle stelle se ti rimproveri per",
"Sentiti libero di ricordare a chi vuoi bene",
"Ma c'e' anche Venere allineata con Plutone che ti ricompensera' con",
"Certamente la persona che ti ama ti regalera'",
"Alla prossima occasione, un tuo vicino di casa ti sorprendera' con",
"Ma non finisce qui, troverai proprio nel tuo letto",
"Come se non bastasse, scoprirai che tutti hanno capito che desideri",
"A confortarti avrai sempre con te",
"Insisti e tieni duro: troverai, fuori dal tunnel,",
"E' ora di dare una svolta alla tua vita con",
"La cosa migliore da fare e' mettere al centro di tutto",
"D'altronde, questa girandola di novità finira' con",
"Oltretutto, desidererai di non aver perso",
"Non fai altro che pensare ai bei tempi, quando sapevi con sicurezza di avere",
"Invece di temporeggiare, provvedi a nascondere a chi sai tu",
"Libera tutte le tue energie con",
"Il vortice dei sentimenti, alla fine, produrra'",
"Ma, quando sembrera' tutto perduto, troverai",
"Come grande sorgente di conforto troverai",
"E' ora di ricambiare i piaceri che ricevi con",
"Pero' nulla ti dara' calore e conforto come",
"Per fortuna lascerai in eredita' ai tuoi pronipoti almeno",
"Inoltre, andando a fare spesa, ti sorprendera'",
"Ma quest'oroscopo puo' svelarti in esclusiva che tua suocera adora",
"In realta' scoprirai che tua suocera tenta di nascondere",
"Questa insoddisfazione che provi sparira' appena ti procurerai",
"La tua vita e' una ricerca continua che finira' solo con",
"Le tue sicurezze sono vere? Forse faresti meglio ad affrontare",
"Ti serve tanto coraggio, ma alla fine potrai affrontare",
"Preparati alle novita', pero'. Quando stasera alzerai le lenzuola troverai",
"Attenzione, chi ti sta vicino adesso usa al posto del filo interdentale",
"E' il momento della rinascita. E' inutile rattristarsi per",
"Ma conta i minuti che ti separano dal prossimo mese, perche' solo allora ti troverai bene con",
"Il tuo destino e' come un canguro: dal suo marsupio estrarra'",
"Per fortuna hai un coraggio da leone che ti permettera' di sconfiggere",
"La tua vita e' come una cozza: tra le sue valve tiene",
"Navigando nel mare delle tempeste, incontrerai",
"Ma alla fine saprai sopravvivere con"
);

$frase4 = array(
"una degna sepoltura",
"un tatuaggio a forma di stufa",
"lo spazzolino vecchio di due anni",
"un po' di ali di pipistrello nel minestrone",
"la voce da usignolo",
"un souffle' con escargot",
"l'encefalopatia spungiforme (BSE)",
"un bel 2 al superenalotto",
"l'alito pesante",
"una festa di compleanno",
"una visita allo zoo",
"una visita dallo psicanalista",
"un'esibizione dal vivo delle Lollipop",
"la lettiera del gatto",
"i brufoli sul naso",
"il sapone intimo dimenticato accanto al bide'",
"un sasso nello stagno",
"il camion dello spurgo",
"mezz'ora di relax sulla tazza",
"un appuntamento dal dentista",
"l'abbonamento a ''Topolino''",
"un abbonamento all'''Enciclopedia dell'uncinetto''",
"un buon idromassaggio",
"un'invasione di cavallette",
"due fette di mortadella",
"un panino con la finocchiona",
"un herpes sul labbro inferiore",
"lo strozzino che ti aspetta dietro l'angolo",
"il tuo magro conto in banca",
"una bella inversione ad U sull'autostrada",
"il coraggio di farla finita",
"il gas che hai lasciato aperto in cucina",
"una martellata in testa al tuo partner",
"il conto del dentista",
"la schiuma da barba al gusto di fragola",
"un'epidemia di pidocchi",
"la biancheria da lavare",
"gli avanzi del pranzo di ieri",
"il profumo delle ascelle",
"un invito a cena con il marito di Maurizio Costanzo",
"l'euroconvertitore del presidente del consiglio",
"un'epidemia di ebola",
"una rapina all'ufficio postale",
"un mandato di cattura",
"il tuo partner chiuso nell'autolavaggio",
"la tua propensione per il mestiere piu' antico del mondo",
"un perizoma leopardato",
"un bisonte che ti insegue",
"la zucca avariata nel frigo",
"il cinghiale che dorme in camera tua",
"la torta della nonna",
"la depilazione ascellare",
"il richiamo della natura",
"un salto nell'iperspazio",
"una furto al supermercato",
"la tua colf senza permesso di soggiorno",
"la persona che stai ricattando",
"una bombetta puzzolente",
"l'aspirapolvere che funziona al contrario",
"uno scambio di personalita'",
"le 60 pulci che popolano la tua stanza",
"una crisi di cleptomania",
"una relazione con l'idraulico",
"un arzillo ottantenne che ti terra' compagnia",
"alien sulla terra",
"il figlio di Godzilla",
"un articolo su di te in ''Donna Moderna''",
"le bacchette che hai rubato al ristorante cinese",
"uno stufato di muflone",
"uno sformato di ghiande",
"una zecca nell'inguine",
"il gelato al gusto di cane",
"un gelato al gusto di cammello",
"un falso in bilancio",
"un cofanetto di unghie tagliate",
"le 42 puntate di Heidi",
"l'esplosivo innescato nel cassonetto",
"il frigorifero da sbrinare",
"il tuo gatto che ha divorato la bimba dei vicini",
"i parassiti dei piccioni",
"la visita delle Fiamme Gialle",
"il tuo vero volto malvagio",
"il tuo vero volto perverso",
"la collezione di slip rubati",
"la cassapanca con dentro la nonna",
"la fossa biologica",
"il frigorifero con dentro nonna",
"i gamberoni assassini",
"il tuo cane impanato",
"i gamberetti carnivori",
"un sistema di telesorveglianza",
"la cocacola con l'aspirina",
"un'amica ninfomane",
"l'uomo che ti ama segretamente",
"una cena con Wonder Woman",
"un'amica perversa",
"un cane per amico",
"l'ordigno bellico sotto la tua abitazione"
);

$a = mt_rand(0, count($frase1)-1);
$b = mt_rand(0, count($frase2)-1);
$c = mt_rand(0, count($frase3)-1);
$d = mt_rand(0, count($frase4)-1);

return 'Oroscopo di questa settimana:<br /> '.$frase1[$a].' '.$frase2[$b].'. '.$frase3[$c].' '.$frase4[$d].'.';

}
